/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CNGStation {
  'id' : bigint,
  'status' : StationStatus,
  'city' : string,
  'name' : string,
  'pricePerKg' : number,
  'isActive' : boolean,
  'address' : string,
  'phone' : string,
  'operatingHours' : string,
}
export type StationStatus = { 'closed' : null } |
  { 'open' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStation' : ActorMethod<
    [string, string, string, string, number, StationStatus, string, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStation' : ActorMethod<[bigint], undefined>,
  'getAllCitiesGrouped' : ActorMethod<
    [],
    [
      Array<[string, string]>,
      Array<[string, string]>,
      Array<[string, string]>,
      Array<[string, string]>,
    ]
  >,
  'getAllStations' : ActorMethod<[], Array<CNGStation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStation' : ActorMethod<[bigint], CNGStation>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'preloadSampleData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByCity' : ActorMethod<[string], Array<CNGStation>>,
  'searchByPriceRange' : ActorMethod<[number, number], Array<CNGStation>>,
  'updateStation' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      number,
      StationStatus,
      string,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];