/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StationStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CNGStation = IDL.Record({
  'id' : IDL.Nat,
  'status' : StationStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'pricePerKg' : IDL.Float64,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'operatingHours' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        StationStatus,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStation' : IDL.Func([IDL.Nat], [], []),
  'getAllCitiesGrouped' : IDL.Func(
      [],
      [
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
      ],
      ['query'],
    ),
  'getAllStations' : IDL.Func([], [IDL.Vec(CNGStation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStation' : IDL.Func([IDL.Nat], [CNGStation], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'preloadSampleData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByCity' : IDL.Func([IDL.Text], [IDL.Vec(CNGStation)], ['query']),
  'searchByPriceRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(CNGStation)],
      ['query'],
    ),
  'updateStation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        StationStatus,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StationStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CNGStation = IDL.Record({
    'id' : IDL.Nat,
    'status' : StationStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'pricePerKg' : IDL.Float64,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'operatingHours' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          StationStatus,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStation' : IDL.Func([IDL.Nat], [], []),
    'getAllCitiesGrouped' : IDL.Func(
        [],
        [
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        ],
        ['query'],
      ),
    'getAllStations' : IDL.Func([], [IDL.Vec(CNGStation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStation' : IDL.Func([IDL.Nat], [CNGStation], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'preloadSampleData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByCity' : IDL.Func([IDL.Text], [IDL.Vec(CNGStation)], ['query']),
    'searchByPriceRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(CNGStation)],
        ['query'],
      ),
    'updateStation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          StationStatus,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };